contact         : "info@software-carpentry.org"
facebook_url    : "https://www.facebook.com/SoftwareCarpentry"
github_url      : "https://github.com/swcarpentry"
google_plus_url : "https://plus.google.com/u/0/114244759874490019250/posts"
rss_url         : "http://software-carpentry.org/feed.xml"
swc_prefix      : "http://software-carpentry.org"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
people : {
    "ahmadia.a" : "Aron Ahmadia",
    "anderson.c" : "Carlos Anderson",
    "antonioletti.m" : "Mario Antonioletti",
    "aruliah.d" : "Dhavide Aruliah",
    "bernabeu.m" : "Miguel Bernabeu",
    "blanco-cuaresma.s" : "Sergi Blanco Cuaresma",
    "blischak.j" : "John Blischak",
    "bostroem.a" : "Azalee Bostroem",
    "bray.e" : "Erik Bray",
    "broekmans.o" : "Onno Broekmans",
    "brown.amy" : "Amy Brown",
    "brown.ct" : "C. Titus Brown",
    "bryan.j" : "Jennifer Bryan",
    "buske.o" : "Orion Buske",
    "cabral.sheeri" : "Sheeri Cabral",
    "cannam.c" : "Chris Cannam",
    "chapman.h" : "Hanah Chapman",
    "chuang-howe.a" : "Adina Chuang Howe",
    "chue-hong.n" : "Neil Chue Hong",
    "cooper.j" : "Jonathan Cooper",
    "cossou.c" : "Christophe Cossou",
    "cozzini.s" : "Stefano Cozzini",
    "cranston.k" : "Karen Cranston",
    "davenport.e" : "Emily Davenport",
    "davis.m" : "Matt Davis",
    "dickson.r" : "Ross Dickson",
    "ely.j" : "Justin Ely",
    "elza.dethe" : "Dethe Elza",
    "enbody.r" : "Richard Enbody",
    "figueira.l" : "Luis Figueira",
    "foertter.f" : "Fernanda Foertter",
    "gidden.matt" : "Matt Gidden",
    "gramfort.a" : "Alexandre Gramfort",
    "gustavsen.j" : "Julia Gustavsen",
    "guy.t" : "Tommy Guy",
    "hansen.m" : "Michael Hansen",
    "hart.t" : "Ted Hart",
    "hauser.e" : "Elliot Hauser",
    "hetherington.j" : "James Hetherington",
    "hettrick.s" : "Simon Hettrick",
    "hinsen.k" : "Konrad Hinsen",
    "huff.k" : "Katy Huff",
    "ivanov.p" : "Paul Ivanov",
    "jackson.m" : "Mike Jackson",
    "jones.d" : "David Jones",
    "kerr.j" : "Jessica Kerr",
    "ketcheson.david" : "David Ketcheson",
    "kitzes.j" : "Justin Kitzes",
    "konrad.b" : "Bernhard Konrad",
    "koop.d" : "David Koop",
    "lagesen.k" : "Karin Lagesen",
    "lawson.a" : "Ainsley Lawson",
    "lewis.chloe" : "Chloe Lewis",
    "limare.n" : "Nicolas Limare",
    "mandli.kyle" : "Kyle Mandli",
    "mcglinn.d" : "Dan McGlinn",
    "mcgough.s" : "Steve McGough",
    "mckellar.j" : "Jessica McKellar",
    "mctavish.ej" : "Emily Jane McTavish",
    "merrelli.aronne" : "Aronne Merrelli",
    "morris.b" : "Ben Morris",
    "morrison.j" : "James Morrison",
    "nederbragt.l" : "Lex Nederbragt",
    "nielsen.c" : "Charlene Nielsen",
    "olson.r" : "Randy Olson",
    "pawlik.a" : "Aleksandra Pawlik",
    "pennekamp.f" : "Frank Pennekamp",
    "peterson.j" : "Joshua L. Peterson",
    "pickens.c" : "Caitlyn Pickens",
    "pipitone.j" : "Jon Pipitone",
    "punch.bill" : "Bill Punch",
    "ram.k" : "Karthik Ram",
    "rokem.a" : "Ariel Rokem",
    "scopatz.a" : "Anthony Scopatz",
    "selik.m" : "Michael Selik",
    "shelton.j" : "Jeffrey Shelton",
    "smith.a" : "Andrew Smith",
    "smith.j" : "Josh Smith",
    "sufi.s" : "Shoaib Sufi",
    "supp.s" : "Sarah Supp",
    "teal.t" : "Tracy Teal",
    "terrel.a" : "Andy Terrel",
    "trimble.will" : "Will Trimble",
    "viana.a" : "Alex Viana",
    "vanderplas.jacob" : "Jake VanderPlas",
    "varoquaux.n" : "Nelle Varoquaux",
    "varoquaux.g" : "Gael Varoquaux",
    "waugh.b" : "Ben Waugh",
    "white.e" : "Ethan White",
    "williams.l" : "Lynne Williams",
    "wilson.g" : "Greg Wilson",
    "wilson.p" : "Paul Wilson",
    "wilson.r" : "Robin Wilson",
    "woods.c" : "Christopher Woods",
    "yu.terri" : "Terri Yu",
    "yunis.enas" : "Enas Yunis",
    "zarrabeitia.l" : "Luis Zarrabeitia"
}
