markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
pygments        : true
contact         : "info@software-carpentry.org"
facebook_url    : "https://www.facebook.com/SoftwareCarpentry"
google_plus_url : "https://plus.google.com/+Software-carpentryOrg"
github_url      : "https://github.com/swcarpentry"
rss_url         : "http://software-carpentry.org/feed.xml"
swc_prefix      : "http://software-carpentry.org"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
vm_url          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtd05FekRId05DLXM&amp;export=download"
exclude         : [branding, data, tmp, swc.tpl]
